language: java
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- "./gradlew build -s -i"
after_success:
- '[ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] && ./gradlew
  artifactoryPublish -s -i'
env:
  global:
  - secure: QkWjmNjqBGPJZmAZsvXv89vNCs3seLPH0A4OftuAxvGWQagCpgb6Xz75YAVrU+kOuSIQfTlI4lf9njB1yxTGtw/nQLfdCADo6Vm5czc0FAQWLI3wEL9eitlY3GKYSSlpURVzlXFSiK1+OiML4xE+bn8qXVZ3rjyg2eJ+ySeM+XzWhN+ASSzuhHOfzTkgdwT0vB7U3z09n/f35aIMuTGjWS8rxa5lUEN9Tx5rPT0QXLBE5PQL7pEI1+QY1a6u7+F0tP3WQRp9U2h3u6wlp/TcFXE+FFz5Vz5WYeQEjT6s3Yh9PdMSDieO0M9XVG0CFHrLFXcSzcweq7+pwkAKTmJRCP8agQnTHXsRNQwDlEucws8wy272CJwn1144Q9/pJUzwtot+Cgm/Spw0yUVy6S8ypBLvkjGeiKyRNOT0KMvdkjVdf7tpHCogq1dpGXrg8PW3mqw8fQzSOJ+cMW8D6BaqhANLEnUjrca8NOXUHTFiPiBtd3+RGybpwJSUQizZnNi2bFy5ShxhtUCetEh3uBwJLqEun6QcQI+ZFZHqlWGM7K675XOKTrUAW84ctJa4FE8J7hJ6vleOWML8J4wa4Zo6p3bmAK2qEt4OCcPhaw5Pq6kn6ahhejOfUjx9Hor5WgLZNC9ueutKo041WrB5cKoXBCv+F7T4qXLfYi6XT/b68fE=
  - secure: SJkTHZKYWM3ZAu+MO4bzVSqTH6wfhUZ4spgemHpDYK+/qWBSYDI7Vx5BHvf/nfkAMNhi9rq1PCT0fXr8qSsxD/d79klnWfU13zQmizj2zL17a+vByEC2Q9EDOse0X8LGEGBc8X5t+PIiPCeYuUbGmteOO+UbqjvNMaVu1tQJxsR3EKXH35WRp31EgSkRQSRyUlZAx3xPfwc5zpqxEFg6Im+94Ef2l1NpeKTxiNdJsvaDYGZ6Xq39zIdEQ1GeAN8h6BJRTnpC5Q0PQGjDsrsKPlBMJfOR7OjtYk6q/Dz6aYa1abMGazyFfFtbO7gVvmPFiyYW2HcChZ8WdWbCa7zV34a5Rw9Kgq34tgikUbijipa8FoatXGStdMYmHVzsuGzsqb+pyJcIiO0T0PDyAmKsqTq167Wjhj7e1DcNavsKdVRYuatHrz/YyT/b4/K0j/f8F9oXDwMzJcJOlTUu1gndZYI6Gd9QnNoQIRsiksfFEY8HJyZrj1RmWUHk4h2q4itKy3eWDbs2qUuiB7oatHsHk4qCNZKAuooAVAPjhkKGcH45BTsr/GTskXoWzk1gIx9pLrNswdK2vwRvYkgoTrEytpnbP7MAFieaOHoA4ru8JN9Z4KSI1HZPzUafKQqWwztOzpszBaL3+ISKgSo2F9JrxVCePQDEATCQxvKGRNfieYk=
